@startuml
package AP4A_project{
    class Server{

    }

    class Scheduler{

    }

    package Sensors{
        class Sensor{

        }

        Sensor "1..1" o--> "1..1" Server: notify

        class SensorBool{

        }

        class SensorFloat{

        }

        class SensorInteger{

        }

        Sensor <|-- SensorBool
        Sensor <|-- SensorFloat
        Sensor <|-- SensorInteger

        Scheduler "1..1" o--> "0..*" Sensor
    }

    class Data<template T>{

    }

    SensorBool --|> Data: Data<bool>
    SensorFloat --|> Data: Data<float>
    SensorInteger --|> Data: Data<int>
}
@enduml